### ISSUE TITLE
Why use Promise._immediateFn here?

### ISSUE THREAD

**Issue by kingstone3** [taylorhakes/promise-polyfill#102]
https://github.com/taylorhakes/promise-polyfill/blob/acc989fe54a8ace00aa73cbd62b974a847bb0d9f/src/index.js#L45

I tried to delete Promise._immediateFn and the result is still correct. Why do I need to put the callback function in Promise._immediateFn?

**Comment by taylorhakes** [comment]
@kingstone3 What do you mean the result is correct? Do you mean all the tests pass? That function is necessary because promises must be asynchronous according to the spec.

In the example below the assert will fail without the `_immediateFn` because `.then` will be called synchronously instead of asynchronously.

```js
let result = null;
Promise.resolve(10).then((val) => result = val);
assert(result === null);
```

**Comment by kingstone3** [comment]
You are right, I forgot that .then is always an asynchronous call
