### ISSUE TITLE
Exception not rejected?

### ISSUE THREAD

**Issue by it-xtech-dev** [taylorhakes/promise-polyfill#106]
Hello,

I have included promise-polyfill iniside my typescript project. I use it like below:

```
import Promise from 'promise-polyfill';

var test = new Promise((resolve,reject) => {
  throw "test exception";
});
test.catch((error) => { throw error; });
```

Once compiled and executed inside browser only thing I get is this console warning:
_Possible Unhandled Promise Rejection: test exception_

**Is it intended behavior?**

When I exclude the import and add script directly inside html (<script src="https://cdn.jsdelivr.net/npm/promise-polyfill@8/dist/polyfill.min.js"></script>) behaviour is different (an exception | error is thrown to console);

**Comment by taylorhakes** [comment]
@it-xtech-dev That is expected. You have thrown an exception in the `catch` but not provided a `catch` handler for it. If you run the same code in Node JS with native promises, it does the same thing. Chrome provides a handler, so that you can log them.
https://developer.mozilla.org/en-US/docs/Web/API/Window/unhandledrejection_event#Basic_error_logging

It doesn't do that with 
```
<script src="https://cdn.jsdelivr.net/npm/promise-polyfill@8/dist/polyfill.min.js"></script>
```
because that script doesn't run if native promises are in the environment already.

I recommend handling that rejection correctly to avoid the warning.
