### ISSUE TITLE
Shimming setImmediate via Promise.immediateFn won't work in non-CommonJS environments

### ISSUE THREAD

**Issue by alex3683** [taylorhakes/promise-polyfill#12]
The following expression would use `immediateFn`, if it was defined previously on a global `Promise` object:
```js
var asap = Promise.immediateFn || (typeof setImmediate === 'function' && setImmediate) ||
function(fn) { setTimeout(fn, 1); };
```
Thus to achieve this I'd have to do something like this in advance:
```js
Promise = {
   immediateFn: function() { /* my shim implementation */ }
};
// or
Promise = function() {};
Promise.immediateFn = function() { /* my shim implementation */ };
```

But if I do this, the shim will never be installed because of this line at the end of the script:
```js
} else if (!root.Promise) {
root.Promise = Promise;
}
```
I already defined `Promise` myself, so it won't be shimmed. Worse: If `Promise` was defined before by the browser, I just broke it. So perhaps checking for the necessity of shimming should be left completely to the user and the module should simply return `Promise` or define an AMD compatible export.

**Comment by taylorhakes** [comment]
Thanks for reporting the bug. `

`Promise.immediateFn` was not usable in it's current state. It could never use the global Promise either because it was looking at the Polyfill Promise https://github.com/taylorhakes/promise-polyfill/blob/master/Promise.js#L16 because of function hoisting. Defining Promise.immediateFn doesn't work because `asap` is already bound.

I added a new API `Promise._setImmedateFn(fn)` . You can pass your callback fn there.

Example use:
```
\\ include file
if (Promise.._setImmedateFn) {
  Promise._setImmediateFn(function(fn) {
    setTimeout(fn, 10);
  });
}
```
I added a couple of tests to catch this next time.

**Comment by alex3683** [comment]
Thanks for that fast fix. I can confirm, it works :+1:

**Comment by taylorhakes** [comment]
Great! Closing this issue.
