### ISSUE TITLE
prototype methods

### ISSUE THREAD

**Issue by DarkPark** [taylorhakes/promise-polyfill#13]
Is there a reason why some of your methods in prototype and some not?

**Comment by taylorhakes** [comment]
Yes, prototype methods are visible to the outside world, essentially public. It is common pattern to put private methods on prototype, but prefix with an underscore. i.e. `Promise.prototype._privateFunc`.

 Since this library is a polyfill, I tried to make it as close to the built-in `Promise` as possible. The built-in `Promise` doesn't expose any underscore methods. 

You can make true private methods using a closure and calling it like `fn.apply(this, args)`. You still get the same performance benefits as the prototype methods, but the functions are not exposed to the outside world on the prototype. Does that make sense?

**Comment by DarkPark** [comment]
thank you for detailed explanation
I haven't check the native Prototype global object to see the same public methods
so now it's clear
