### ISSUE TITLE
Something I don't understand about your code

### ISSUE THREAD

**Issue by dactac** [taylorhakes/promise-polyfill#30]
I've been learning js and I'm a little confused with your _resolve_ function, why did you deal with Promise instance separately with thenable objects? By doing so,you added a new state of "3" to the Promise,which is not quite good in my opinion. 
I've checked the previous version of this,and found that you didn't deal with it as you did now.So there must be a reason.Would you be kind and tell me why?
Thanks in advance.

` function resolve(self, newValue) {

//some code
      if (newValue && (typeof newValue === 'object' || typeof newValue === 'function')) {
        var then = newValue.then;
        if (newValue instanceof Promise) {
          self._state = 3;
          self._value = newValue;
          finale(self);
          return;
        } else if (typeof then === 'function') {
          doResolve(bind(then, newValue), self);
          return;
        }
      }
//some code
  }`

**Comment by taylorhakes** [comment]
@dactac The reason for state `3` is because it's possible to have a memory leak in a really long Promise chain. Each promise keeps a reference to the previous Promise and it's never broken. State `3` allows the library to shortcut the long chain and resolve a Promise with the value of the next Promise. This only works if the Promise is from this library. Other Promise libraries (thenables) may not work the same way, so it's not possible to use the same logic. That is why it checks if it's an instance of Promise.

Here is the code that is used later during the callback stage

https://github.com/taylorhakes/promise-polyfill/blob/master/promise.js#L41

**Comment by dactac** [comment]
Can you be more specific? An example would be appreciated.
Cause from what I understand, given promise A,B,C and A is resolved by B,and B by C.
With previous code , C._deffereds gets to resolve B with it's value ,and thus keeps a reference to B,and the same with A and B.
But with current version, A._value points to B. and B._value points to C. Isn't that a chain?

**Comment by taylorhakes** [comment]
deferreds are cleared, correct. 

You are correct that `current version, A._value points to B. and B._value points to C`. The state 3 allows A._value point to C and remove the intermediate B that is not necessary to resolving A.
