### ISSUE TITLE
Consider enabling the daily build in TravisCI

### ISSUE THREAD

**Issue by limonte** [taylorhakes/promise-polyfill#96]
Thank you @taylorhakes for taking care of https://github.com/taylorhakes/promise-polyfill/issues/95

The conversation is locked there, so I will continue here. CI stands for **continuous** integration. In the unstable ecosystem of front-end dependencies, it's essential to build software on a daily basis.

If the build is green but happened a month ago, that does not guarantee that is will be successful today.

Enabling daily builds is as easy as three mouse-clicks, docs: https://docs.travis-ci.com/user/cron-jobs/

**Comment by taylorhakes** [comment]
Hi limonte. Thanks for the suggestion. I gave it some thought and I agree that a build a month ago does not mean it is green today, but I think that would be very rare for this library. It would mean that a dependency changed (this library has no dependencies) or that the build environment changed. If the build environment changed, a failed build on a random day is most likely a case of a false positive versus an actual issue. It seems highly unlikely that a new version of node will come out and break compatibility. I feel false positives are a high concern and will force me to keep an eye on the library on a daily basis, which I would like to avoid. As you have seen, Travis is not perfect and the build can fail because Travis has an issue.

Do you know of other cases where the build breaks and it's an actual issue that needs fixing? My current feeling is if there are no code changes, it still safe to assume this library is working.

**Comment by limonte** [comment]
All your points are valid @taylorhakes

Except maybe the from my experience, TravisCI is quite reliable and produces false failures quite rarely. 

What I'm concerned about is the CX (contributor experience). Here's the example: a build was green a month ago and in the meantime it became red, but you don't know about it as it was not triggered.

And then, external contributor sends a PR, a build for that PR fails, contributor starts investigation of a failure, realizes that it's not related to his/her change, but to the project CI configuration. Will he/she get a positive experience of that? I don't think so. 

Anyways, the happiness of contributors might me out of your priorities scope, and I'll totally understand if you will not enable daily builds.

**Comment by limonte** [comment]
Worksforme 👍 Thanks for clarifying the details, @taylorhakes!

**Comment by limonte** [comment]
FWIW, TravisCI is fine, your configuration is not :)

Here's the screenshot of my daily builds in [CatLight](https://catlight.io/), all nice a green without manual restarts:

![image](https://user-images.githubusercontent.com/6059356/45264112-f7e94780-b43f-11e8-9b5f-bac552a2dc98.png)

**Comment by taylorhakes** [comment]
@limonte What is the issue with the configuration? I am happy fix any issue you can find. 

Your builds being green has no bearing on whether there is or isn't an issue with Travis. You can't declare Travis bug free because you haven't run into a bug. There are millions of bugs in apps you use all the time that you haven't experienced. Here is a wiki page that describes the logic issue https://en.wikipedia.org/wiki/Evidence_of_absence
